"""empty message

Revision ID: 23c491bc9194
Revises: c5524418c64e
Create Date: 2017-08-18 09:53:56.044693

"""

# revision identifiers, used by Alembic.
revision = '23c491bc9194'
down_revision = 'c5524418c64e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clubes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clubes')
    # ### end Alembic commands ###
