"""empty message

Revision ID: 26d45d154cc7
Revises: 23c491bc9194
Create Date: 2017-08-18 09:54:39.721169

"""

# revision identifiers, used by Alembic.
revision = '26d45d154cc7'
down_revision = '23c491bc9194'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
