"""empty message

Revision ID: c5524418c64e
Revises: a0ef55bfc5a9
Create Date: 2017-08-18 08:14:30.079068

"""

# revision identifiers, used by Alembic.
revision = 'c5524418c64e'
down_revision = 'a0ef55bfc5a9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socios', sa.Column('activo', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socios', 'activo')
    # ### end Alembic commands ###
